### ISSUE TITLE
Refactor OnnxInferenceModel to reduce code duplication

### ISSUE THREAD

**Issue by ermolenkodev** [Kotlin/kotlindl#358]
I think it would be a good idea to unify this (predictSoftly) method with `predictRaw` (as a separate PR).

_Originally posted by @juliabeliaeva in https://github.com/JetBrains/KotlinDL/pull/356#discussion_r852313090_

**Comment by zaleslaw** [comment]
Keep in mind the predictSoftly method for the TensorFlow models before refactoring

The initial idea of the predictSoftly method is the following: return the vector of probabilities instead of the class label calculated via argmax on the vector of probabilities.

The semantic for the predictRaw is more common – to return just low-level output with a few tensors, for example, not just 1D vector

**Comment by zaleslaw** [comment]
@ermolenkodev is this ticket closed by the PR? If yes, please wire it together with PR and close
